base_conf:
  seed: 42
  task_type: countdown
  model_path: <MODEL_PATH_QWEN2_5_1_5B_INSTRUCT>
  data_path: <DATA_PATH_COUNTDOWN_TRAIN>
  project_name: review-cser-countdown
  start_id: 0
actor_conf:
  device: cuda
  worker_port: <OMITTED_ACTOR_WORKER_PORT>
  filter: true
  batchsize: 6
  num_generations: 8
  keep_num: 8
  max_prompt_length: 200
  max_new_tokens: 2048
  first_send_size: 192
  send_size: 128
  per_start: 1
  save_iter: 100
  epoch_num: 100
buffer_conf:
  device: cpu
  expsize: 192
  first_send_size: 192
  send_size: 128
  per_start: 1
learner_conf:
  device: cuda
  n_gpus: 1
  worker_port: <OMITTED_LEARNER_WORKER_PORT>
  loss_type: vespo
  per: true
  expsize: 24576
  batchsize: 192
  mini_batchsize: 12
  lr: 0.000002
  kl_loss_coef: 0.001
  cliprange: 0.2
  clip_ratio_c: 3.0
  gamma: 0
  a_decay: 0.95
  per_gamma: 0.5
  save_iter: 10
  kl_iter: 100000
  send_iter: 1
  start_samples: 192
  max_trainstep: 10000
logging_conf:
  log_level: INFO
